---
format: 
  docx:
    reference-doc: my_styles.docx
    number-sections: true
title: "Title"
bibliography: refs.bib
csl: estuaries-and-coasts.csl
crossref: 
  fig-title: Fig.
author:
  - Marcus W Beck:
      email: mbeck@tbep.org
      orcid: 0000-0002-4996-0059
      institute: [TBEP]
      correspondence: true
  - Kerry Flaherty-Walia:
      email: kfwalia@tbep.org
      orcid: 0000-0002-6032-0570
      institute: [TBEP]
      correspondence: false
  - Sheila Scolaro-Moffatt:
      email: sscolaro@tbep.org
      orcid: 0000-0003-3220-3737
      institute: [TBEP]
      correspondence: false

institute:
  - TBEP: Tampa Bay Estuary Program, 263 13th Ave S., Suite 350, St. Petersburg, Florida 33701 USA

filters: 
  - templates/scholarly-metadata.lua
  - templates/author-info-blocks.lua
  
execute: 
  echo: false
  warning: false
  ft.keepnext: false
  ft.align: left
---

```{r}
#| results: hide
library(knitr)
library(flextable)
library(here)
library(dplyr)
library(tidyr)

source(here('R/funcs.R'))
```

## Abstract {.unnumbered}

Text

*Key words*:

{{< pagebreak >}}

## Introduction 

importance of monitoring

local context

difficulty in precision/accuracy, examples with known biases

methods to assess precision/accuracy

goals: present a reproducible framework for assessing precision among disparate groups, determine if training efforts have improved precision using the framework

## Methods

history of transect monitoring

note that we can't run trend analyses on converted scores - these are always rescaled each year, since the primary goal is to serve as a motivating example each year.  To assess trends, we really need to look at how avg raw differences have changed over time (see scratch.R). 

## Results


## Discussion

limitations - truth is not known

what didn't work:

* attempts at discounting group differences by how variable they were between species.  this was done for a species across transects, small sample sizes (e.g., a species at two or three transects) made this measure noisy and not a meaningful assessment of group consistency.  Alternatively, the getween-group variation is a more meaningful measure of certainty, but it describes an entirely different source of variation. 


{{< pagebreak >}}

## Figures {.unnumbered}

{{< pagebreak >}}

## Tables {.unnumbered}


{{< pagebreak >}}

## Data Availability {.unnumbered}

All data and analysis code for this manuscript is available on GitHub at <https://github.com/tbep-tech/seagrasstraining-manu>.

## Acknowledgments {.unnumbered}


## References {.unnumbered}